# docker-compose.yml

version: '3.7'

services:
  mindpulse-api:
    build: .
    container_name: mindpulse-api
    volumes:
      - ./:/app
      - node_modules:/app/node_modules/
    ports:
      - '3000:3000'
    depends_on:
      - mindpulse-db
      - mindpulse-redis
    env_file:
      - ./.env
    logging:
      driver: json-file

  mindpulse-db:
    restart: always
    build: ./pgdata
    container_name: mindpulsedb
    environment:
      POSTGRES_DB: mindpulsedevdb
      POSTGRES_USER: mindpulse
      POSTGRES_PASSWORD: mindpulse!23
    volumes:
      - mindpulse-pgdata:/var/lib/postgresql/data
    logging:
      driver: json-file
    ports:
      - 8001:5432

  mindpulse-redis:
    image: redis
    container_name: cache
    logging:
      driver: json-file
    ports:
      - 6379:6379

volumes:
  mindpulse-pgdata:
  node_modules:
